name: Build and Deploy

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - name: Set GitHub credentials
      run: |
        git config user.name $name
        git config user.email $email
      env:
        name: 'Damian Suidgeest'
        email: 'damiansuidgeest@gmail.com'
    - name: Install dependencies
      run: npm ci
    - name: Deploy to GitHub pages
      run: npm run deploy
