name: Build and Deploy

on:
  push:
    branches:
    - main
  workflow_run:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: npm ci
    - name: Deploy to GitHub pages
      run: npm run deploy
